### ISSUE TITLE
difference between django-rest-framework-sso and oauth2

### ISSUE THREAD

**Issue by FingerLiu** [namespace-ee/django-rest-framework-sso#1]
Hi. I came here from stackoverflow, I‘ve glanced README, Is my understanding correct:
 **django-rest-framework-sso is a simplified version of oauth2**, and since oauth2 basiclly
focus on authorization,  django-rest-framework-sso also contains authentication feature?

**Comment by lnagel** [comment]
Yes, you could say that - our aim was to provide something much simpler than oauth2 for SSO use cases. 

This library provides both authentication (user identification) and authorization (permissions identification) using two types of JWT tokens. 

Let me know if I can help you in trying it out :)

**Comment by FingerLiu** [comment]
Thanks for your reply, my target is to build a sso for an enterprise, and the enterprise may has other sytem which is not build by us. I wonder if this project can satisfy the situation since it does not has a protocol as common as oauth2. If it can satisy the situation I would like to have a try. THX

**Comment by lnagel** [comment]
The protocol being used is JWT and it has implementations in all popular languages, so for sure the interoperability should not be an issue. Please check https://jwt.io/ for further reference.

We use the PyJWT implementation ourselves https://pyjwt.readthedocs.io/en/latest/ for backend and another library for parsing the tokens in the frontend javascript code as well.
