### ISSUE TITLE
How can i add reset password ?

### ISSUE THREAD

**Issue by Barolina** [namespace-ee/django-rest-framework-sso#11]

**Comment by lnagel** [comment]
Maybe you could describe your plan in a bit more detail?

In our projects, we invalidate issued session tokens when a person changes their password. The session token used to make the password change request is not invalidated.

**Comment by Barolina** [comment]
I want to  add enpoint change_passwort

**Comment by lnagel** [comment]
@Barolina No problem. You might want to revoke other sessions also when you change password:

```python
user_sessions = SessionToken.objects.active().filter(user=request.user)
if getattr(request, "auth", None) is not None and isinstance(request.auth, dict):
    session_id = request.auth["sid"]
    user_sessions = user_sessions.exclude(id=session_id)
user_sessions.update(revoked_at=timezone.now())
```

**Comment by Barolina** [comment]
Thanks you
