### ISSUE TITLE
Implementation between different servers on the cloud?

### ISSUE THREAD

**Issue by jagwardo** [namespace-ee/django-rest-framework-sso#12]
- I want to put a django SSO server on the cloud in its own server, like "sso.example.com".
- Then I want to use a service let's call it "service1.example.com".
- We basically have two different servers now, each with their own OS.
-
**Question**:
How can "service1.example.com" communicate with django sso server so it can authenticate the tokens and retrieve user information settings?

**Comment by lnagel** [comment]
Hi! The whole point of JWT is that tokens are authenticated without communication between the servers using cryptographic signatures.

Any information you need on the other servers, you'll have to embed into the short-lived authorization tokens that the sso server issues.

Please see the README:

https://github.com/namespace-ee/django-rest-framework-sso#additional-data-in-authorization-tokens

**Comment by jagwardo** [comment]
More details is needed, I have a problem with public keys since i keep getting "Unauthorized token signing key." exception.

below is for primary app
```
REST_FRAMEWORK_SSO = {
    'CREATE_AUTHORIZATION_PAYLOAD': 'django_sso.users.adapters.create_authorization_payload',
    'IDENTITY': 'django_sso',
    'SESSION_AUDIENCE': ['django_sso'],
    'AUTHORIZATION_AUDIENCE': ['django_sso', 'service1'],
    'ACCEPTED_ISSUERS': ['django_sso'],
    'PUBLIC_KEYS': {
        'django_sso': 'django_sso/keys/sso-service.pem',
    },
    'PRIVATE_KEYS': {
        'django_sso': 'django_sso/keys/sso-service.pem',
    },

    'ENCODE_ALGORITHM': 'RS256',
    'DECODE_ALGORITHMS': None,
    'VERIFY_SIGNATURE': True,
    'VERIFY_EXPIRATION': True,
    'VERIFY_ISSUER': True,
    'VERIFY_AUDIENCE': True,
    'VERIFY_SESSION_TOKEN': True,
    'EXPIRATION_LEEWAY': 0,
    'SESSION_EXPIRATION': None,
    'AUTHORIZATION_EXPIRATION': datetime.timedelta(seconds=300),

    'KEY_STORE_ROOT': None,

    'AUTHENTICATE_HEADER': 'Bearer',

}
```

and below is for a service that consumes the jwt:

```
REST_FRAMEWORK_SSO = {
    'AUTHENTICATE_PAYLOAD': 'service1.utils.authentication.authenticate_payload',
    'VERIFY_SESSION_TOKEN': False,
    'IDENTITY': 'service1',
    'ACCEPTED_ISSUERS': ['django_sso'],
    'PUBLIC_KEYS': {
        'service1': 'config/keys/sso-service.pem',  # only public key in this file
    },
    'AUTHENTICATE_HEADER': 'Bearer',
}
```

**Comment by lnagel** [comment]
The problem might be that you are not defining KEY_STORE_ROOT and that the key id's do not match.

`django_sso/keys/sso-service.pem` => gets converted to key_id `django_sso/keys/sso-service`, but no such path exists on the jwt consumer side.

I would reccommend setting the correct path to and including the keys folder in both servers, and then dropping the `'django_sso/keys/` and `config/keys/` prefixes. Then your key id will be just `sso-service` which matches on both.

**Comment by lnagel** [comment]
Updated the recommended config as well in README:

https://github.com/namespace-ee/django-rest-framework-sso/commit/b1dbdfddd76f59af02133d5d9416f78845234c32

**Comment by jagwardo** [comment]
It works well now, thanks a lot.
I hope more work is done on the documentation so it can be more clear, its implementation is quite good but not as clear in the first try.
