### ISSUE TITLE
JWT in cookie

### ISSUE THREAD

**Issue by mekanix** [namespace-ee/django-rest-framework-sso#13]
It would be nice if JWT could be stored in HttpOnly (and in production Secure, too) cookie. Any plans to implement it?

**Comment by lnagel** [comment]
Could you describe your use case in some detail please?

**Comment by mekanix** [comment]
It's mostly security and storing the token. Local and session storage are not ideal places, as JS libraries and 3rd party adons can access them. Also, current problem we have is using DRF UI as there's nothing that "remembers" the token to be passed in headers. If JWT is in the cookie, that means browser takes care of when it's sent (and how) to the backend, that way making DRF UI usable (maybe there's another way I do not know about?). If the cookie is HttpOnly, that nothing except browser can reach JWT, so JS is cut off from it. If it has Secure flag, it will be transmitted only over HTTPS ensuring that misconfiguration of load balancer "disables" login.

I did the same for the little framework I'm working on based on Flask, so if I can be of any assistance implementing this, I would be glad to do it.

**Comment by lnagel** [comment]
I understand what you're saying. You are actually free to store the JWT tokens as you wish.

This library is for authentication - where the JWT token is sent to the server in the Authorization header and does not use any kind of cookies or session storage.
