### ISSUE TITLE
Discord SSO Method Get Not Allowed

### ISSUE THREAD

**Issue by cclloyd** [namespace-ee/django-rest-framework-sso#15]
I'm trying to add Discord auth to a DRF project using this framework (react frontend, DRF backend).

There's a button on the UI that links to the following oauth link:  `https://discord.com/api/oauth2/authorize?client_id=713381169349263361&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fsession&response_type=code&scope=identify` (most permissions cut out for brevity)

Yet when I run this, after authorizing with Discord, it redirects back to my app and gives me an error

> Method GET not allowed.

When I try to do /authorize instead, it gives

> Authentication credentials not provided.

I might just be misunderstanding something here, but what might I be doing wrong?  

I added the DEFAULT_AUTHENTICATION_CLASSES in REST_FRAMEWORK and set REST_FRAMEWORK_SSO to `'AUTHENTICATE_PAYLOAD': 'api.authentication.authenticate_payload'` as described in the README.  Is there something else I'm missing?

The end goal was to allow a user to sign in with Discord, then have that create an account in Django (instead of having normal registration enabled).

**Comment by lnagel** [comment]
This project does not provide oauth2 support.
