### ISSUE TITLE
Can't run celery tasks - There is no Authentication header there

### ISSUE THREAD

**Issue by neomib** [namespace-ee/django-rest-framework-sso#16]
Hi,
I have a microservice Django system in which I run celery tasks. The thing is that  one of my celery tasks calls a function that
makes a request to another microservice and it has no knowledge of the current "Authentication" Header.  

It is supposed to run in the background even when the session is terminated.

I tried to create a token using your functions before executing the request. But o success.

Any ideas?

**Comment by lnagel** [comment]
Closing the topic since there aren't any code samples or specific errors that I could comment on.
