### ISSUE TITLE
Why do i have a error jwt decode  if i  use to only public key my other app ?

### ISSUE THREAD

**Issue by Barolina** [namespace-ee/django-rest-framework-sso#17]
if i make this 

```REST_FRAMEWORK_SSO = {
    'AUTHENTICATE_PAYLOAD': 'otherapp.authentication.authenticate_payload',
    'VERIFY_SESSION_TOKEN': False,
    'IDENTITY': 'otherapp',
    'ACCEPTED_ISSUERS': ['myapp'],
    'KEY_STORE_ROOT': '/srv/otherapp/keys',
    'PUBLIC_KEYS': {
        'myapp': ['public.pem', ],  # only public keys in these files
    },
}````

I have  a error    "Error decoding signature."

**Comment by lnagel** [comment]
This error message is caused by the jwt module raising `jwt.exceptions.DecodeError` which might indicate that the token is malformed.

**Comment by Barolina** [comment]
I understand  this,   but  i need  used to a both private/public key in the same file  as well in  other app  ?

**Comment by lnagel** [comment]
No, that's not required at all.
In fact it's normal that the other apps only have the public key part.

**Comment by lnagel** [comment]
Ah, maybe one more thing: the filename of the .pem file should match on all servers.

**Comment by Barolina** [comment]
No  if i used  only public key in file i had jwd decode error.  
if i used  as well a file ( a both private/public key in the same file) i had good.

**Comment by lnagel** [comment]
Then probably the filenames don't match, this sounds like it indeed.

**Comment by Barolina** [comment]
thanks
