### ISSUE TITLE
Why don't  SESSION_EXPIRATION  change?

### ISSUE THREAD

**Issue by Barolina** [namespace-ee/django-rest-framework-sso#18]
I set: 

```
"SESSION_EXPIRATION": timedelta(days=1)
```

But SESSION_EXPIRATION is always 5 minutes.

**Comment by lnagel** [comment]
I don't fully understand the problem, please write a more detailed report.

The session expiration is encoded into the token at the time the token is issued and it's not dependent on the SESSION_EXPIRATION parameter after that.

**Comment by Barolina** [comment]
I have set time for session_token .

my settings

```

REST_FRAMEWORK_SSO = {
    'CREATE_SESSION_PAYLOAD': 'config.payload.create_session_payload',
    'CREATE_AUTHORIZATION_PAYLOAD': 'config.payload.create_authorization_payload',
    'IDENTITY': IAM_NAME_SYSTEM,
    'SESSION_AUDIENCE': [IAM_NAME_SYSTEM],
    'AUTHORIZATION_AUDIENCE': [IAM_NAME_SYSTEM] + env.list('DJANGO_SSO_AUDIENCE'),
    'ACCEPTED_ISSUERS': [IAM_NAME_SYSTEM],

    'KEY_STORE_ROOT': os.path.normpath(env.get_value('DJANGO_SSO_KEY_PATH', default='keys')),
    'PRIVATE_KEYS': {IAM_NAME_SYSTEM: [env.get_value('DJANGO_SSO_PUBLIC_KEYS', default='test-2048.pem'),
                                       env.get_value('DJANGO_SSO_PRIVATE_KEYS', default='test-1024.pem')]
                     },
    'PUBLIC_KEYS': {IAM_NAME_SYSTEM: [env.get_value('DJANGO_SSO_PUBLIC_KEYS', default='test-2048.pem'), ]},
    'VERIFY_SIGNATURE': True,
    'VERIFY_EXPIRATION': True,
    'VERIFY_ISSUER': True,
    'VERIFY_AUDIENCE': True,
    'VERIFY_SESSION_TOKEN': True,
    'AUTHORIZATION_EXPIRATION': timedelta(seconds=300),
    "SESSION_EXPIRATION": timedelta(days=1),       ------------------------------

    'AUTHENTICATE_HEADER': 'JWT',
}

```

But sessio token live  only 5 minutes. must 1 day

**Comment by lnagel** [comment]
Please also explain whether this is about new tokens or existing tokens.

**Comment by Barolina** [comment]
exist,  i say about 

```  url(r'^session/', obtain_session_token), ```

**Comment by lnagel** [comment]
Existing tokens aren't modified by that view. The setting applies only for new tokens issued by that view.

**Comment by Barolina** [comment]
sorry, yes, applies only for new tokens, but not applies, value  always 5 minutes. I can't set  new time value for session  token

**Comment by Barolina** [comment]
Sorry.  I try:  What this:

1 
```
REST_FRAMEWORK_SSO = {
     "SESSION_EXPIRATION": timedelta(days=1)
      'AUTHENTICATE_HEADER': 'JWT',
}
```

2   curl POST  "/session/"   in 14:20

my rsponse :  

```eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6ImlhbSJ9.eyJ0b2tlbiI6ImF1dGgiLCJzaWQiOiI0ZjNlODUwMi1hZTg1LTRhMzctYmU5ZC01OTJkNTBiNTJjY2EiLCJ1aWQiOjMsImVtYWlsIjoic29sb3dfbGFyaXNhQG1haWwucnUiLCJzY29wZXMiOltdLCJpc3MiOiJpYW0iLCJhdWQiOlsiaWFtIiwiYWlzdW16Il0sImV4cCI6MTYwNjM5MDE5NiwiaWF0IjoxNjA2Mzg5ODk2fQ.AdCUI_9Ob49NUt72pHUosr_QKDVqOsCe67uKhFd9b5iM6C12APuKao2ocqnPApzCJAy68WS1nUMXV3EABuMcU_ppWuwWVY-dzu-3DuIUNpzKOMZfkKTf_HL3AkNyBQ_cO_Uxpt0FOiaJ5xCUXVZMTETxXmVfyz_AV4El0nMMHnYihen41bEGDqtoSzNwSVc34w1BMwZ26KDKzwRuSkQtHhEcmydS6UvibaToSBzhPYw3EixlSCHragYBcjOv7EPA_CMJOxc4KMwTZyr7WpDRBOVqbhRJ_dMIYsiREz4imsv-GIzBREh_zULroC3gY37atHagD90SaRK6qubP3lpl3w````

**Why:   exp = 14:30 **

![изображение](https://user-images.githubusercontent.com/5443003/100345412-56844700-2ff3-11eb-88ed-9b3b12ed3fd9.png)

**Comment by lnagel** [comment]
To be honest, I can't explain this behaviour. There are no other defaults set at 5 minutes either.

If you can make available an example project that displays this behaviour, then I could investigate further.

Right now it works for me and I don't see any way how it could not.

**Comment by lnagel** [comment]
Please post a copy of your urls.py

**Comment by lnagel** [comment]
Found a clue in your JWT token, it has "token": "auth"

It seems you have wired the `ObtainAuthorizationTokenView` into `/session/` (instead of `ObtainSessionTokenView`).

By default, session token expiration is not set.

Authorization tokens for other services have indeed 5 minute expiry because of their short lived nature.

**Comment by lnagel** [comment]
```
        'SESSION_EXPIRATION': None,
        'AUTHORIZATION_EXPIRATION': datetime.timedelta(seconds=300),
```

**Comment by Barolina** [comment]
thanks you
