### ISSUE TITLE
Need help with "detail": "Unauthorized token signing key." message

### ISSUE THREAD

**Issue by Wanna101** [namespace-ee/django-rest-framework-sso#19]
I am having a challenge on the authorization token side.  Here's what I have so far with 2 apps:

Primary login app:

I am able to get the token after the POST of username and password.

"Other app":

Replaying that token on the "Other app" I get:

"detail": "Unauthorized token signing key."

What is this message telling me and how can I debug this further?

Thanks!

**Comment by Wanna101** [comment]
I manage to get past the above as I didn't update the 'myapp' on the authorization app to the appropriate name. 

    'PUBLIC_KEYS': {
        'myapp': ['myapp-20200410.pem', 'myapp-20180101.pem'],  # only public keys in these files
    },

I am now with a new problem of a HTTP 403:  "detail": "Incorrect authentication credentials.".  Any ideas on why the credentials are incorrect?

With some print statements it looks like I am failing in the def decode_jwt_token(token) in the util.py file since I printed some "HERE" statements and it does not get past this line but throws the exception:

127     payload = jwt.decode(                                                                              
  1     ¦   jwt=token,                                                                                     
  2     ¦   key=public_key,                                                                                
  3     ¦   verify=api_settings.VERIFY_SIGNATURE,                                                          
  4     ¦   algorithms=api_settings.DECODE_ALGORITHMS or [api_settings.ENCODE_ALGORITHM],                  
  5     ¦   options=options,                                                                               
  6     ¦   leeway=api_settings.EXPIRATION_LEEWAY,                                                         
  7     ¦   audience=api_settings.IDENTITY,                                                                
  8     ¦   issuer=unverified_issuer,                                                                      
  9     )

**Comment by Wanna101** [comment]
Looks like I need that verify to be False?  It appears that allowed the request to pass.  Am I doing this right?

**Comment by Wanna101** [comment]
New issue on 'AUTHORIZATION_EXPIRATION': datetime.timedelta(seconds=10) placed inside "myapp' but is not being honored in 'otherapp'

It appears that the token does not expire.  Requests to "otherapp" continue to respond with a http 200.

**Comment by Wanna101** [comment]
I even printed out the values in the decode_jwt_token(token) routine in utils.py and it shows the payload has the info but it is still returning 200 OK.  I placed 'AUTHORIZATION_EXPIRATION': datetime.timedelta(seconds=10) in both 'myapp' and 'otherapp':

 13     public_key, key_id = get_public_key_and_key_id(issuer=unverified_issuer, key_id=unverified_key_id)                                    
 12     if DEBUG:                                                                                                                             
 11     ¦   print(f"*********** HERE7 ***********")                                                                                           
 10     ¦   print(f"options verify_exp: {api_settings.VERIFY_EXPIRATION}")                                                                    
  9     ¦   print(f"options auth_exp_date: {api_settings.AUTHORIZATION_EXPIRATION}")                                                          
  8     ¦   print(f"options verify_iss: {api_settings.VERIFY_ISSUER}")                                                                        
  7     ¦   print(f"options verify_aud: {api_settings.VERIFY_AUDIENCE}")                                                                      
  6                                                                                                        

web_1        | *********** HERE7 ***********
web_1        | options verify_exp: True
web_1        | options auth_exp_date: 0:00:10
web_1        | options verify_iss: True
web_1        | options verify_aud: True

**Comment by Wanna101** [comment]
Looks like I need to do the comparison on the "otherapp" for request.auth.get(claims.EXPIRATION_TIME)
 and compare it with "now" (ie. int(time.time())).  I did this and made the custom message response to deny the request.  Is this not built in the library?

**Comment by lnagel** [comment]
> Looks like I need that verify to be False? It appears that allowed the request to pass. Am I doing this right?

Verify should definetly be set to True, otherwise the SSO signatures are not validated.

> New issue on 'AUTHORIZATION_EXPIRATION': datetime.timedelta(seconds=10) placed inside "myapp' but is not being honored in 'otherapp'
> 
> It appears that the token does not expire. Requests to "otherapp" continue to respond with a http 200.

This might indicate a time sync issue between the servers. To know for sure, then please post your JWT token payload data here. You can obtain it using the debugger on this site https://jwt.io/

> Looks like I need to do the comparison on the "otherapp" for request.auth.get(claims.EXPIRATION_TIME)
> and compare it with "now" (ie. int(time.time())). I did this and made the custom message response to deny the request. Is this not built in the library?

This feature is built in into the jwt python library already, it is not necessary to write your own code for this. There must be another issue at play here.

Again to know for sure, then please decode your JWT tokens using the debugger and paste the payload data.
