### ISSUE TITLE
How to integrate Client django project with Primary project. 

### ISSUE THREAD

**Issue by adilmalik393** [namespace-ee/django-rest-framework-sso#2]
I have also two projects. I am making the Project1 as SSO Primary app and this will be used for user authentication and authorization. But issue is that i couldn't find out how to set up the client project.

**Comment by lnagel** [comment]
@adilmalik393 The client project setup defined in README (where myapp is the client).

Example settings for project that only accepts tokens signed by myapp for otherapp:

```
REST_FRAMEWORK_SSO = {
    'AUTHENTICATE_PAYLOAD': 'otherapp.authentication.authenticate_payload',
    'VERIFY_SESSION_TOKEN': False,
    'IDENTITY': 'otherapp',
    'ACCEPTED_ISSUERS': ['myapp'],
    'PUBLIC_KEYS': {
        'myapp': 'keys/myapp_public_key.pem',
    },
}
```
