### ISSUE TITLE
Unauthorized token signing key.

### ISSUE THREAD

**Issue by adilmalik393** [namespace-ee/django-rest-framework-sso#3]
Encoding is being done with private key and key_id in header is actually private key path, But when payload needed to decoded in AuthorizationView, key_id is fetched from header and for decoding, public key is needed to get form get_public_key_and_key_id in keys.py. Now the key_id passed to this function is private_key_id and we are expecting to get public key. So that's why it throws error.

    REST_FRAMEWORK_SSO = {
    'CREATE_SESSION_PAYLOAD': 'rest_framework_sso.utils.create_session_payload',
    'CREATE_AUTHORIZATION_PAYLOAD': 'rest_framework_sso.utils.create_authorization_payload',
    'ENCODE_JWT_TOKEN': 'rest_framework_sso.utils.encode_jwt_token',
    'DECODE_JWT_TOKEN': 'rest_framework_sso.utils.decode_jwt_token',
    'AUTHENTICATE_PAYLOAD': 'rest_framework_sso.utils.authenticate_payload',
    'ENCODE_ALGORITHM': 'RS256',
    'DECODE_ALGORITHMS': None,
    'VERIFY_SIGNATURE': True,
    'VERIFY_EXPIRATION': True,
    'VERIFY_SESSION_TOKEN': True,
    'EXPIRATION_LEEWAY': 0,
    'SESSION_EXPIRATION': None,
    'AUTHORIZATION_EXPIRATION': datetime.timedelta(seconds=300),
    'IDENTITY': 'authserver',
    'SESSION_AUDIENCE': ['authserver'],
    'AUTHORIZATION_AUDIENCE': ['authserver'],
    'ACCEPTED_ISSUERS': ['authserver'],
    'KEY_STORE_ROOT': None,
    'PUBLIC_KEYS': {
        'authserver': 'authserver/public_key.pem'
    },
    'PRIVATE_KEYS': {
        'authserver': 'authserver/private_key.pem'
    },
   'AUTHENTICATE_HEADER': 'JWT',
}

**Comment by uroybd** [comment]
I'm getting the same error, any way to solve it?

**Comment by bpereto** [comment]
This fixes it for me, but I don't know yet if it weakens the security:
```
+++ b/.venv/lib/python3.6/site-packages/rest_framework_sso/utils.py 2018-05-07 13:11:15.122181383 +0200
@@ -99,7 +99,7 @@
     if api_settings.ACCEPTED_ISSUERS is not None and unverified_issuer not in api_settings.ACCEPTED_ISSUERS:
         raise InvalidIssuerError('Invalid issuer')
 
-    public_key, key_id = get_public_key_and_key_id(issuer=unverified_issuer, key_id=unverified_key_id)
+    public_key, key_id = get_public_key_and_key_id(issuer=unverified_issuer)
 
     options = {
         'verify_exp': api_settings.VERIFY_EXPIRATION,
```

**Comment by lnagel** [comment]
@uroybd @bpereto Sorry for not noticing this earlier!

You should put both your private and public key into the same .pem file, because the filename base is the key_id.

The whole key_id logic was made to support key rotation between multiple servers. You first start adding new public keys to slave servers
```
'PUBLIC_KEYS': {
    'authserver': ['authserver/myservice-20180101.pem', 'authserver/myservice-20180918.pem']
},
```

and then afterwards you can replace the key in private keys too.
