### ISSUE TITLE
QuerySetReadableMixin is not defined

### ISSUE THREAD

**Issue by johnsonc** [namespace-ee/django-rest-framework-sso#5]
When trying to add the Custom class as given in the README, I get this error. 
Also, the current branch does not have this anywhere in the code. Is this an external library Mixin?

**Comment by johnsonc** [comment]
11
     12
---> 13 class AuthorizationTokenSerializer(QuerySetReadableMixin, serializers.Serializer):
     14     account = serializers.HyperlinkedRelatedField(
     15         queryset=Account.objects.all(),

NameError: name 'QuerySetReadableMixin' is not defined

**Comment by madisvain** [comment]
@johnsonc please just remove this QuerySetReadableMixin mixin from your usage. This is an internal mixin we use and it should not be in the documentation.

We will remove it from the documentation also. Thank you for reporting this.

**Comment by lnagel** [comment]
Fixed in 5e571d4c1349c31d374ec06f57f36648f8a6bfc7
